# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# === Basic configuration ===

# Your application's name
appname: "app"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# === Engines ===
#
# NOTE: All the engine configurations need to be under a single "engines:"
# key.  If you uncomment engine configurations below, make sure to delete
# all "engines:" lines except the first.  Otherwise, only the last
# "engines:" block will take effect.

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"
template: "template_toolkit"

# engines:
#   template:
#     template_toolkit:
#       # Note: start_tag and end_tag are regexes
#       start_tag: '<%'
#       end_tag:   '%>'

# session engine

session: "Redis"

engines:
  session:
    Redis:
      cookie_name: "sessionid"
      is_http_only: 1
      redis_server: "172.17.0.5:6379"
      redis_password: ""
      session_duration: 86400
      # cookie_duration: 86400
      redis_name: "my_connection_name"
      redis_serialization:
        # Use Sereal as serialization module:
        module: "Dancer2::Session::Redis::Serialization::Sereal"
        # Serialization module configuration:
        # Use snappy compression
        compression: "snappy"
      # server: "172.17.0.5:6379" # Change this to your Redis server address and port
      # password: "" # Optional: If your Redis server requires a password, set it here
      # database: 0 # Optional: If you want to use a specific Redis database, set its index here


#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.
#
#engines:
#  session:
#    Simple:
#      cookie_name: testapp.session
#
#engines:
#  session:
#    YAML:
#      cookie_name: eshop.session
#      is_secure: 1
#      is_http_only: 1
